### PR TITLE
Chapter6

### PR DESCRIPTION
**Pull request by mmargenot**
Working on making covariance matrix symmetric

### CODE REVIEW

**Comment by twiecki** [comment]
- Add short comment why we use Bartlett decomposition (with link to wikipedia).
- Have you tried with pure Metropolis and find_MAP?
- It's great that the LKJ prior works but I'd say we stash that to keep true to the original. Iit would be great to have that as a tutorial/example in the pymc3 docs, though.

**Comment by mmargenot** [comment]
The code that I have for the LKJ prior has a common start with the existing example on LKJ in the pymc3 docs, actually. The main difference is that I made the creation of the covariance matrix a deterministic variable in the model so I could get its trace directly. It could be a natural extension to what's already there.

**Comment by twiecki** [comment]
image

Hm, seems like we're getting quite different answers with Metropolis. Have you checked convergence?

**Comment by twiecki** [comment]
If it's difficult to converge, you can either try setting `blocked=False` in the Metropolis sampler, or use NUTS as before.

**Comment by mmargenot** [comment]
covariance_traceplot_ch6

**Comment by mmargenot** [comment]
It seems to be converging, but there's a lot going on at once.

**Comment by mmargenot** [comment]
Here is the traceplot for NUTS
covariance_traceplot_nuts_ch6

**Comment by mmargenot** [comment]
Here is the traceplot of NUTS and Metropolis on top of each other. Red is NUTS, Blue is Metropolis.

layered_traceplot

**Comment by mmargenot** [comment]
First one is NUTS, second is Metropolis

burned_traceplots
burned_traceplots_2

**Comment by twiecki** [comment]
I think the key problem is initialization (and using NUTS as Metropolis has a hard time converging). Here is a model where I can get good recovery for Wishart:

``` python
def mvn_wishart(rets, nsample=2000, n_assets=2):
    # zero-center
    rets -= np.mean(rets, axis=0)

    init_wishart = np.cov(data.T)
    with pm.Model() as model:
        cov_matrix = pm.WishartBartlett("cov", 
                                        init_wishart, 
                                        n_assets+5,
                                        testval=init_wishart)

        x_ = pm.MvNormal('returns', 0, 
                         T.nlinalg.matrix_inverse(cov_matrix), observed=rets)

        step = pm.NUTS()
        trace = pm.sample(nsample, step)

    return trace
```

This required a pymc3 change (https://github.com/pymc-devs/pymc3/commit/641c0f53fee12f2cdd4661ad02603f291d9b54dd) so that WishartBartlett can be passed init values.

Here's a model where I get good recovery using LKJ:

``` python
def mvn_lkjprior_general(rets, nsample=2000, advi_n=50000, n_assets=2):

    """ 
    The LKJ (Lewandowski, Kurowicka and Joe) log-likelihood.
    The LKJ distribution is a prior distribution for correlation matrices.
    If n = 1 this corresponds to the uniform distribution over correlation
    matrices. For n -> oo the LKJ prior approaches the identity matrix.
    ========  ==============================================
    Support   Upper triangular matrix with values in [-1, 1]
    ========  ==============================================
    Parameters
    ----------
    n : float
        Shape parameter (n > 0). Uniform distribution at n = 1.
    p : int
        Dimension of correlation matrix (p > 0).
    Notes
    -----
    This implementation only returns the values of the upper triangular
    matrix excluding the diagonal. Here is a schematic for p = 5, showing
    the indexes of the elements::
        [[- 0 1 2 3]
         [- - 4 5 6]
         [- - - 7 8]
         [- - - - 9]
         [- - - - -]] """

    # zero-center
    rets -= np.mean(rets, axis=0)

    n_elem = n_assets * (n_assets - 1) / 2
    tri_index = np.zeros([n_assets, n_assets], dtype=int)
    tri_index[np.triu_indices(n_assets, k=1)] = np.arange(n_elem)
    tri_index[np.triu_indices(n_assets, k=1)[::-1]] = np.arange(n_elem)

    sample_corr = np.corrcoef(data.T)
    lkj_init = sample_corr[np.triu_indices(n_assets, k=1)]
    sd_init = np.std(data, axis=0)
    with pm.Model() as model:
        sigma = pm.Lognormal('sigma', 0, 1, 
                             shape=n_assets, testval=sd_init)

        #print('sigma\n', sigma.tag.test_value)
        C_triu = pm.LKJCorr('C_triu', n=1, p=n_assets,
                            testval=lkj_init)
        #print('C_triu\n', C_triu.tag.test_value)
        C = T.fill_diagonal(C_triu[tri_index], 1.)
        #print('C\n', C.tag.test_value)
        sigma_diag = T.nlinalg.diag(sigma)
        #print('sigma_diag\n', sigma_diag.tag.test_value)
        cov = pm.Deterministic('cov', T.nlinalg.matrix_dot(sigma_diag, C, sigma_diag))
        #print('cov\n', cov.tag.test_value)
        tau = pm.Deterministic('tau', T.nlinalg.matrix_inverse(cov))
        #print('tau\n', tau.tag.test_value)
        #mu = pm.MvNormal('mu', 0, tau, shape=n_assets)

        x_ = pm.MvNormal('returns', 0, tau, observed=rets)

        step = pm.NUTS()
        trace = pm.sample(nsample, step)
```

Can you adapt the code and see if it fixes the issues we were seeing?

**Comment by mmargenot** [comment]
Here's the correlation matrix using WishartBartlett, initializing it with the data's covariance.

corr_wishart_initialized

**Comment by mmargenot** [comment]
I converted the handling of the data to pandas.

These are the results with WishartBartlett (WITH testval = np.cov(stock_returns)):
pandas_wishart_corr
These are the results with LKJcorr (with NO initialization):
pandas_lkj_corr

If I run LKJcorr with initial values for the correlations it does not work. The posterior samples are simply the prior (expert_prior_params) repeated 5000 times (the number of samples).

**Comment by twiecki** [comment]
OK, I think I figured it out. Both models were failing but for different reasons:
LKJ:

``` python
import pymc3 as pm
import theano.tensor as T
from theano.tensor.nlinalg import matrix_inverse, diag, matrix_dot

# Create triangular indices to construct the covariance matrix
prior_mu = np.array([x[0] for x in expert_prior_params.values()])
prior_std = np.array([x[1] for x in expert_prior_params.values()])

n_var = len(prior_mu)
n_elem = int(n_var * (n_var - 1) / 2)
tri_index = np.zeros([n_var, n_var], dtype=int)
tri_index[np.triu_indices(n_var, k=1)] = np.arange(n_elem)
tri_index[np.triu_indices(n_var, k=1)[::-1]] = np.arange(n_elem)

sample_corr = stock_returns.corr().values
lkj_init = sample_corr[np.triu_indices(n_var, k=1)]

with pm.Model() as model:
    corr_triangle = pm.LKJCorr("corr", n=1, p=n_var, testval=lkj_init)
    corr_matrix = pm.Deterministic("corr_matrix", T.fill_diagonal(corr_triangle[tri_index], 1))
    sigma_diag = diag(pm.Lognormal("sigma_diag", mu=prior_std, tau=1, shape=4, testval=stock_returns.std()))
    cov_matrix = pm.Deterministic("covariance", matrix_dot(sigma_diag, corr_matrix, sigma_diag))

    mu = pm.Normal("returns", prior_mu, 1, shape=4, testval=stock_returns.mean())
    obs = pm.MvNormal("observed returns", mu, matrix_inverse(cov_matrix), observed=stock_returns)

    step = pm.NUTS()
    trace = pm.sample(5000, step=step)
```

As you can see, I turned sigma on the diagonal into a proper prior, before it was just a determinstic which means we don't even estimate the variance of the data which causes funkiness for the model.

Wishart:

``` python
import pymc3 as pm
import theano.tensor as T
from theano.tensor.nlinalg import matrix_inverse, diag, matrix_dot

prior_mu = np.array([x[0] for x in expert_prior_params.values()])
prior_std = np.array([x[1] for x in expert_prior_params.values()])
init = stock_returns.cov()

with pm.Model() as model:
    cov_matrix = pm.WishartBartlett("covariance", 
                                    np.diag(prior_std**2), 
                                    10, 
                                    testval=init)

    mu = pm.Normal("returns", prior_mu, 1, shape=4)

    obs = pm.MvNormal("observed returns", mu, matrix_inverse(cov_matrix), observed=stock_returns)
    step = pm.NUTS()
    trace = pm.sample(5000, step=step)
```

Here the issue was the second argument passed to `WishartBartlett` which was set to the number of data points which is way too high and causes an extremely restrictive prior for the off-diagonals which explains the pattern we were seeing.

**Comment by twiecki** [comment]
For simplicity, I'd say we roll with the WishartBartlett, model is much more concise and I think the API for LKJ can be improved to be more like it.

**Comment by mmargenot** [comment]
So I ran the WishartBartlett model with 10 degrees of freedom, the way you suggested, and it looks great:

dof_10

And then I ran it with a prior on the degrees of freedom, `dof = pm.DiscreteUniform("dof", 4, 16)` and it looks great as well:

dof_discrete_uniform

**Comment by twiecki** [comment]
Looks great indeed. lets just set it to `n_assets + 1` (=5).

**Pull request merged**
