### PR TITLE
Chapter 5

### PR DESCRIPTION
**Pull request by mmargenot**

### CODE REVIEW

**Comment by mmargenot** [comment]
Currently working on the text to go along with the code

**Comment by twiecki** [comment]
It is also rude to hand someone over a distribution when all the asked for was an estimate. -> *he/she (they?) (not your typo but might as well fix it).

**Comment by twiecki** [comment]
"We can turn this reasoning around: the least-squares model is not try to predict the best (according to a stock-loss definition of predict). "

**Comment by twiecki** [comment]
"We will attempt to implement Tim's winning solution using PyMC" -> PyMC3

**Comment by twiecki** [comment]
``````
exp_mass_large = pm.Uniform("exp_mass_large", 40, 180)
mass_large = pm.Deterministic("mass_large", np.log(exp_max_large))
``` -> That code does not seem to match with the model below.
``````

**Comment by twiecki** [comment]
`mean = pm.Deterministic("mean", mass_large / f_distance(T.as_tensor(data[:,:2]), halo_position, 240)*\
                    tangential_distance(T.as_tensor(data[:,:2]), halo_position))
` That line break looks pretty bad in nbviewer.

**Comment by twiecki** [comment]
`step = pm.NUTS(scaling=model.dict_to_array(sds))` this should require `is_cov=True`. This is also true for the model below it.

**Comment by twiecki** [comment]
See comments but otherwise looks great!

**Pull request merged**
